name = "cvm"
version = "1.0.0"
description = "Caffeine Version Manager"
licences = ["MIT"]
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.63.0 and < 1.0.2"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.2"
